include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

formatter:
  page_width: 80

linter:
  rules:
    # --- Style ---
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    sort_child_properties_last: true
    use_super_parameters: true
    unnecessary_this: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_lambdas: true
    unnecessary_string_interpolations: true

    # --- Safety ---
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    avoid_returning_null_for_void: true

    # --- Documentation ---
    slash_for_doc_comments: true

    # --- Collections ---
    prefer_collection_literals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_spread_collections: true
    prefer_if_null_operators: true
    prefer_conditional_assignment: true

    # --- Types ---
    avoid_init_to_null: true
    omit_local_variable_types: true
    prefer_typing_uninitialized_variables: true

    # --- Formatting ---
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    empty_catches: true
    empty_statements: true
